import { useContext, useEffect, useState } from "react";
import { DoctorContext } from "../../context/DoctorContext";
import { AppContext } from "../../context/AppContext";
import { toast } from "react-toastify";
import axios from "axios";
import jsPDF from "jspdf";

import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
} from "recharts";

const DoctorProfile = () => {
  const {
    dToken,
    profileData,
    setProfileData,
    getProfileData,
    backendUrl,
    appointments,
  } = useContext(DoctorContext);

  const { currency, slotDateFormat } = useContext(AppContext);

  const [isEdit, setIsEdit] = useState(false);

  useEffect(() => {
    if (dToken) getProfileData();
  }, [dToken]);

  const updateProfile = async () => {
    try {
      const updateData = {
        address: profileData.address,
        fees: profileData.fees,
        available: profileData.available,
      };

      const { data } = await axios.post(
        backendUrl + "/api/doctor/update-profile",
        updateData,
        { headers: { dToken } }
      );

      if (data.success) {
        toast.success(data.message);
        setIsEdit(false);
        getProfileData();
      } else {
        toast.error(data.message);
      }
    } catch (error) {
      toast.error(error.message);
    }
  };

  // 📊 STATS
  const totalAppointments = appointments.length;
  const completedAppointments = appointments.filter(
    (item) => item.isCompleted
  ).length;
  const cancelledAppointments = appointments.filter(
    (item) => item.cancelled
  ).length;

  // 📈 CHART DATA
  const groupedData = {};
  appointments.forEach((item) => {
    const date = slotDateFormat(item.slotDate);
    if (!groupedData[date]) groupedData[date] = 0;
    groupedData[date]++;
  });

  const chartData = Object.keys(groupedData).map((date) => ({
    name: date,
    patients: groupedData[date],
  }));

  // 💎 PRO PDF FUNCTION
  const downloadPDF = () => {
    const doc = new jsPDF();
    const completed = appointments.filter((a) => a.isCompleted);

    // 🎨 HEADER
    doc.setFillColor(99, 102, 241);
    doc.rect(0, 0, 210, 25, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.text("Doctor Patient Report", 20, 15);

    // 👨‍⚕️ Doctor Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);

    doc.text(`Doctor: ${profileData.name}`, 20, 35);
    doc.text(`Speciality: ${profileData.speciality}`, 20, 42);
    doc.text(`Total Patients: ${completed.length}`, 20, 49);

    // 📊 Table Header
    let y = 60;

    doc.setFillColor(240, 240, 240);
    doc.rect(20, y, 170, 10, "F");

    doc.setFontSize(11);
    doc.text("No", 22, y + 7);
    doc.text("Patient", 35, y + 7);
    doc.text("Date", 90, y + 7);
    doc.text("Time", 130, y + 7);
    doc.text("Fees", 160, y + 7);

    y += 12;

    // 📄 Table Data
    completed.forEach((item, index) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      doc.setFontSize(10);

      doc.text(`${index + 1}`, 22, y);
      doc.text(item.userData?.name || "N/A", 35, y);
      doc.text(slotDateFormat(item.slotDate), 90, y);
      doc.text(item.slotTime, 130, y);
      doc.text(`${currency} ${item.amount || 0}`, 160, y);

      y += 8;
    });

    // 📌 Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by Health Bridge", 20, 285);

    doc.save("doctor-report.pdf");
  };

  return (
    profileData && (
      <div className="w-full min-h-screen px-8 py-6 bg-gradient-to-br from-gray-50 to-gray-100">
        <div className="max-w-[1400px] mx-auto flex flex-col lg:flex-row gap-10">

          {/* LEFT PROFILE */}
          <div className="lg:w-[25%] bg-white rounded-2xl shadow-md p-6">

            <div className="flex flex-col items-center text-center">
              <img
                src={profileData.image}
                className="w-28 h-28 rounded-xl object-cover shadow"
                alt=""
              />
              <h2 className="text-xl font-semibold mt-3">
                {profileData.name}
              </h2>
              <p className="text-gray-500 text-sm">
                {profileData.degree} - {profileData.speciality}
              </p>
            </div>

            <div className="mt-5">
              <p className="font-medium text-gray-700">About</p>
              <p className="text-sm text-gray-500 mt-1">
                {profileData.about}
              </p>
            </div>

            <div className="mt-4">
              <p className="text-sm text-gray-500">Fee</p>
              {isEdit ? (
                <input
                  type="number"
                  value={profileData.fees}
                  onChange={(e) =>
                    setProfileData((prev) => ({
                      ...prev,
                      fees: e.target.value,
                    }))
                  }
                  className="border p-2 rounded mt-1 w-full"
                />
              ) : (
                <p className="font-medium">
                  {currency} {profileData.fees}
                </p>
              )}
            </div>

            <div className="mt-4">
              <p className="text-sm text-gray-500">Address</p>
              <p className="text-sm text-gray-600">
                {profileData.address.line1} <br />
                {profileData.address.line2}
              </p>
            </div>

            <div className="mt-4 flex items-center gap-2">
              <input
                type="checkbox"
                checked={profileData.available}
                onChange={() =>
                  isEdit &&
                  setProfileData((prev) => ({
                    ...prev,
                    available: !prev.available,
                  }))
                }
              />
              <span>Available</span>
            </div>

            <div className="mt-6 flex flex-col gap-3">
              {isEdit ? (
                <button
                  onClick={updateProfile}
                  className="bg-indigo-500 text-white py-2 rounded-lg"
                >
                  Save Changes
                </button>
              ) : (
                <button
                  onClick={() => setIsEdit(true)}
                  className="border border-indigo-500 text-indigo-600 py-2 rounded-lg"
                >
                  Edit Profile
                </button>
              )}

              <button className="bg-red-100 text-red-600 py-2 rounded-lg">
                Logout
              </button>
            </div>
          </div>

          {/* RIGHT SIDE */}
          <div className="flex-1 w-full space-y-6">

            {/* GRAPH */}
            <div className="bg-white rounded-2xl shadow-md p-5">
              <p className="font-semibold mb-3">
                Appointments Overview
              </p>

              <ResponsiveContainer width="100%" height={300}>
                <LineChart data={chartData}>
                  <XAxis dataKey="name" />
                  <YAxis />
                  <Tooltip />
                  <Line
                    type="monotone"
                    dataKey="patients"
                    stroke="#6366f1"
                    strokeWidth={3}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>

            {/* STATS */}
            <div className="grid sm:grid-cols-3 gap-5">
              <div className="bg-indigo-100 p-5 rounded-xl">
                <p className="text-sm text-gray-600">Total</p>
                <p className="text-2xl font-semibold">
                  {totalAppointments}
                </p>
              </div>

              <div className="bg-green-100 p-5 rounded-xl">
                <p className="text-sm text-gray-600">Completed</p>
                <p className="text-2xl font-semibold">
                  {completedAppointments}
                </p>
              </div>

              <div className="bg-red-100 p-5 rounded-xl">
                <p className="text-sm text-gray-600">Cancelled</p>
                <p className="text-2xl font-semibold">
                  {cancelledAppointments}
                </p>
              </div>
            </div>

            {/* PATIENT HISTORY */}
            <div className="bg-white rounded-2xl shadow-md p-5">
              <div className="flex justify-between items-center mb-4">
                <p className="font-semibold text-lg">
                  Patient History 🧾
                </p>

                <button
                  onClick={downloadPDF}
                  className="bg-indigo-500 text-white px-4 py-2 rounded-lg text-sm"
                >
                  Download PDF
                </button>
              </div>

              {appointments.filter((item) => item.isCompleted).length === 0 ? (
                <p className="text-gray-400 text-sm">
                  No completed appointments yet
                </p>
              ) : (
                <div className="space-y-3 max-h-[250px] overflow-y-auto">
                  {appointments
                    .filter((item) => item.isCompleted)
                    .map((item, index) => (
                      <div
                        key={index}
                        className="flex justify-between items-center border p-3 rounded-lg"
                      >
                        <div className="flex gap-3 items-center">
                          <img
                            src={item.userData?.image}
                            className="w-10 h-10 rounded-full"
                            alt=""
                          />
                          <div>
                            <p className="font-medium">
                              {item.userData?.name}
                            </p>
                            <p className="text-xs text-gray-500">
                              {slotDateFormat(item.slotDate)} |{" "}
                              {item.slotTime}
                            </p>
                          </div>
                        </div>

                        <p className="text-sm font-medium">
                          {currency} {item.amount}
                        </p>
                      </div>
                    ))}
                </div>
              )}
            </div>

          </div>
        </div>
      </div>
    )
  );
};

export default DoctorProfile;